### ISSUE TITLE
Error using standard json library in dify-sandbox: Operation not permitted

### ISSUE THREAD

**Issue by taisei-13046** [langgenius/dify-sandbox#104]
Hi! I encountered an "Operation not permitted" error when running the following code in the Dify sandbox. The error appears to stem from the import json line, suggesting a lack of necessary permissions for the system call.

```py
# just import standard json library
import json

def main() -> dict:
    return {
        "hello": "hello"
    }

print(main())
```

Log

```
{"code":0,"message":"success","data":{"error":"error: operation not permitted\n","stdout":""}}
```

Would it be necessary to adjust the seccomp config to enable this?

## executed it as follows:

pull image

```shell
docker pull langgenius/dify-sandbox
```

docker run

```shell
docker run -p 8194:8194 langgenius/dify-sandbox
```

curl 

```curl
curl -X POST http://localhost:8194/v1/sandbox/run \
-H "Content-Type: application/json" \
-H "X-Api-Key: dify-sandbox" \
-d '{
  "language": "python3",
  "code": "import json\n\ndef main() -> dict:\n    return {\n        \"hello\": \"hello\"\n    }\n\nprint(main())",
  "preload": "",
  "enable_network": false
}'
```

## As a side note

If remove import json, it works correctly.

```py
def main() -> dict:
    return {
        "hello": "hello"
    }

print(main())
```

curl

```curl
curl -X POST http://localhost:8194/v1/sandbox/run \
-H "Content-Type: application/json" \
-H "X-Api-Key: dify-sandbox" \
-d '{
  "language": "python3",
  "code": "def main() -> dict:\n    return {\n        \"hello\": \"hello\"\n    }\n\nprint(main())",
  "preload": "",
  "enable_network": false
}'
```

Log

```
{"code":0,"message":"success","data":{"error":"","stdout":"{'hello': 'hello'}\n"}}
```

**Comment by AkaiNoCat** [comment]
@taisei-13046 hello, how did you solve this problem?

**Comment by userdsr** [comment]
same problem, how did you resolve it?

**Comment by jimmyzhang610** [comment]
same problem, how did you resolve it?

**Comment by diaolizhi** [comment]
Need to add allowed system calls: 21 access, 79 getcwd, 269 faccessat, 332 statx

Including the system calls that are enabled by default, the complete list is:

`[0,1,2,3,5,8,9,10,11,12,13,14,15,16,21,24,25,35,39,60,79,96,102,105,106,110,131,186,201,202,217,228,230,231,233,234,257,262,269,270,274,275,291,318,332,334]`

**Comment by linview** [comment]
I don't quite understand the solution, 

here is my update in docker-compose.yaml

```yaml
  sandbox:
    image: langgenius/dify-sandbox:0.2.12
    restart: always
    privileged: true
    security_opt:
      - seccomp:unconfined
```

but it’s not working...

any comment?

**Comment by LicsDaSheng** [comment]
@taisei-13046 same problem, how did you resolve it?
