### ISSUE TITLE
nodejs error: morestack on g0\nerror: signal: trace/breakpoint trap\

### ISSUE THREAD

**Issue by dafang** [langgenius/dify-sandbox#19]
Run nodejs code and into this error:

```
{"code":0,"message":"success","data":{"error":"fatal: morestack on g0\nerror: signal: trace/breakpoint trap\n","stdout":""}}
```

Go version: Go 1.21.4

**Comment by dafang** [comment]
This is caused by go 1.21, refer to [here](https://github.com/golang/go/issues/67298)

Solution:

- use go 1.20  or upgrade your go from 1.21 to the latest stable version `go version go1.22.5 linux/amd64`

**Comment by dafang** [comment]
This is caused by go 1.21, refer to [here](https://github.com/golang/go/issues/67298)

Solution:

- use go 1.20  or upgrade your go from 1.21 to the latest stable version `go version go1.22.5 linux/amd64`

**Comment by dafang** [comment]
@Yeuoly

**Comment by Yeuoly** [comment]
Okay, have you already test it? We can upgrade it to the latest and have a CI test for it

**Comment by dafang** [comment]
> Okay, have you already test it? We can upgrade it to the latest and have a CI test for it

Yes, I have upgraded our production and use the latest go to build the main program.
