### ISSUE TITLE
if the module name written in  python-requirements.txt is not the same as "import module_name" , what should i do?

### ISSUE THREAD

**Issue by autel-tangyinghao** [langgenius/dify-sandbox#36]
if the module name written in  python-requirements.txt is not the same as "import module_name" , what should i do?
for example:  aliyun-log-python-sdk==0.9.2   in  python-requirements.txt .   need to  "import aliyun.log"
![image](https://github.com/user-attachments/assets/734c9590-5964-4171-a279-6191b1b8f069)

_Originally posted by @LONGZaixiang in https://github.com/langgenius/dify/issues/4612#issuecomment-2268228195_

**Comment by luckylhb90** [comment]
<img width="953" alt="image" src="https://github.com/user-attachments/assets/aa689cc7-f458-4ccf-9484-bfac0ebcd291">
If you are running a service through docker, you can put the python packages you need into this file.

**Comment by autel-tangyinghao** [comment]
the module name written in  python-requirements.txt...
for example: aliyun-log-python-sdk==0.9.2 in python-requirements.txt . need to "import aliyun.log"

**Comment by Yeuoly** [comment]
pls change to the latest version, select dependencies manually is no longer required.
