### ISSUE TITLE
Pattern python.so: no matching files found

### ISSUE THREAD

**Issue by tclxyida-hu** [langgenius/dify-sandbox#60]
Run ./build/build_amd64.sh 

Error:
Building Python lib
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
Building env
internal/core/runner/python/setup.go:20:12: pattern python.so: no matching files found

**Comment by Yeuoly** [comment]
please using CGO_ENABLED=1
