### ISSUE TITLE
无法使用pycryptodome python库

### ISSUE THREAD

**Issue by NetN1nj4** [langgenius/dify-sandbox#61]
已经安装该库
![image](https://github.com/user-attachments/assets/27bed9c2-b586-4385-807b-73d78b04f94a)
实际调用也没问题
![image](https://github.com/user-attachments/assets/1f971545-2737-4131-ab0a-c15644e3eb98)

工作流中使用代码执行就会报错说找不到该模块
![image](https://github.com/user-attachments/assets/0d424084-86a0-4e76-8390-991c1a98f274)

**Comment by yuweimian-shy** [comment]
需要重新打sandbox的镜像，在打镜像的同时安装第三方库

**Comment by Yeuoly** [comment]
You need to rebuild the image, or using this interface https://github.com/langgenius/dify-sandbox/blob/main/internal/controller/run.go#L45
