### ISSUE TITLE
dify-sandbox: python script's running time gradually increases over time

### ISSUE THREAD

**Issue by lennydou** [langgenius/dify-sandbox#76]
Through long-term observation, it has been noticed that the running time of Python scripts in the sandbox gradually increases over time. After restarting the sandbox, the running time becomes shorter again, only to gradually lengthen as time goes on.

![image](https://github.com/user-attachments/assets/61e41313-dfe2-4105-9ea7-6930c82a655e)

**Comment by Yeuoly** [comment]
fixed #83

**Comment by blackbass64** [comment]
![Image](https://github.com/user-attachments/assets/ac5cc94c-5808-404f-a0b3-03dfea264402)
I’m encountering the same issue in `v0.2.12`.

**Comment by zhj98** [comment]
i ‘m encountering the same issue in v0.2.12,  It keeps increasing without being released as the scheduled task runs every half hour.

![Image](https://github.com/user-attachments/assets/6c1562e6-0030-47b3-835b-3cb203f7771c)
