### ISSUE TITLE
sandbox ssl error and character detection warnings

### ISSUE THREAD

**Issue by meishild** [langgenius/dify-sandbox#79]
When i upgrade sandbox to 0.2.7 use python requests https url error。

/usr/local/lib/python3.10/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer). warnings.warn( meout) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 294, in _get_conn return conn or self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1059, in _new_conn raise ImportError( ImportError: Can't connect to HTTPS URL because the SSL module is not available. json, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send resp = conn.urlopen( File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 768, in urlopen conn = self._get_conn(timeout=pool_timeout) File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 294, in _get_conn return conn or self._new_conn() File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1059, in _new_conn raise ImportError( ImportError: Can't connect to HTTPS URL because the SSL module is not available. error: exit status 255

at 0.2.6 and 0.2.7 also have character detection warnings

<img width="414" alt="image" src="https://github.com/user-attachments/assets/78120cb1-c99e-4d70-8fbc-4df31efe46e7">

**Comment by Yeuoly** [comment]
This has already been fixed, wait for a release
